language: php

php:
  - 7.2
  - 7.3

services:
  - postgresql

before_script:
  - psql -c 'create database catalog;' -U postgres
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - node -v
  - yarn install
  - yarn production

script:
  - vendor/bin/phpunit

cache:
  yarn: true

notifications:
  email: false
