language: php

php:
  - 7.2

services:
  - postgresql

before_script:
  - psql -c 'create database catalog;' -U postgres
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
  - npm install

notifications:
  email: false
