language: php

php:
  - 7.2
  - nightly

services:
  - postgresql

before_script:
  - cp .env.example .env
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit
