version: '3'

volumes:
  # MySQL Data
  postgres-data:
    driver: local
  # Redis Data
  redis-data:
    driver: local

services:
  postgres:
    image: ambientum/postgres:9.6
    container_name: catalog-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=catalog_pass
      - POSTGRES_DB=catalog
      - POSTGRES_USER=catalog_user

  cache:
    image: ambientum/redis:4.0
    container_name: catalog-cache
    command: --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.1-nginx
    container_name: catalog-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.1
    container_name: catalog-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - postgres
      - cache
