INSERT INTO disciplina (descricao) VALUES ('Álgebra Linear');
INSERT INTO disciplina (descricao) VALUES ('Desenho');
INSERT INTO disciplina (descricao) VALUES ('Física Experimental I');
INSERT INTO disciplina (descricao) VALUES ('Tópicos em Tecnologia da Informação');
INSERT INTO disciplina (descricao) VALUES ('Elementos de Lógica Digital');
INSERT INTO disciplina (descricao) VALUES ('Linguagem de Programação I');
INSERT INTO disciplina (descricao) VALUES ('Cálculo Integral e Diferencial I');
INSERT INTO disciplina (descricao) VALUES ('Física I');
INSERT INTO disciplina (descricao) VALUES ('Português Instrumental I');
INSERT INTO disciplina (descricao) VALUES ('Fundamentos de Matemática');
INSERT INTO disciplina (descricao) VALUES ('Cálculo Integral e Diferencial II');
INSERT INTO disciplina (descricao) VALUES ('Fenômenos de Transporte');
INSERT INTO disciplina (descricao) VALUES ('Eletricidade Aplicada');
INSERT INTO disciplina (descricao) VALUES ('Física Experimental II');
INSERT INTO disciplina (descricao) VALUES ('Física II');
INSERT INTO disciplina (descricao) VALUES ('Português Instrumental II');
INSERT INTO disciplina (descricao) VALUES ('Probabilidade e Estatística');
INSERT INTO disciplina (descricao) VALUES ('Estrutura de Dados');
INSERT INTO disciplina (descricao) VALUES ('Linguagem de Programação II');
INSERT INTO disciplina (descricao) VALUES ('Inglês Instrumental');
INSERT INTO disciplina (descricao) VALUES ('Matemática Discreta');
INSERT INTO disciplina (descricao) VALUES ('Eletromagnetismo');
INSERT INTO disciplina (descricao) VALUES ('Arquitetura de Computadores');
INSERT INTO disciplina (descricao) VALUES ('Inteligência Artificial I');
INSERT INTO disciplina (descricao) VALUES ('Métodos Numéricos');
INSERT INTO disciplina (descricao) VALUES ('Química Tecnológica Geral');
INSERT INTO disciplina (descricao) VALUES ('Análise de Algoritmos');
INSERT INTO disciplina (descricao) VALUES ('Linguagens Formais e Autômatos');
INSERT INTO disciplina (descricao) VALUES ('Banco de Dados');
INSERT INTO disciplina (descricao) VALUES ('Linguagem de Programação II');