name: Docker Image CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1', '8.2']

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    #- name: Build the Docker image
    #  run: docker build . --file ./docker/php/Dockerfile --tag research-catalog:latest
    #- name: Run tests
    #  run: docker run research-catalog ./vendor/bin/phpunit
    #- name: Tag docker image
    #  run: docker tag research-catalog:latest research-catalog:$(date +%s)
