name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['7.4', '8.0']

    name: PHP ${{ matrix.php }}

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: catalog
          POSTGRES_USER: catalog_user
          POSTGRES_PASSWORD: catalog_pass
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.travis .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Migrate database
        run: php artisan migrate

      - name: Install yarn dependencies
        run: yarn install

      - name: Execute tests
        run: vendor/bin/phpunit

      #- name: Build the Docker image
      #  run: docker build . --file ./docker/php/Dockerfile --tag research-catalog:$(date +%s)
