name: Docker Image CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./docker/php/Dockerfile --tag research-catalog:latest
    - name: Run tests
      run: docker run research-catalog ./vendor/bin/phpunit
    - name: Tag docker image
      run: docker tag research-catalog:latest research-catalog:$(date +%s)
